# name of the software
name: Redux Docs
# current version of the software
version: 1.0.0
# url of the download button
downloadUrl: https://wordpress.org/plugins/redux-framework/
# licence of the software
license: GPL 3.0+
licenseUrl: https://opensource.org/licenses/gpl-3.0

# list of additional links on the right of the top menu
headerLinks:
  - title: GitHub
    url: https://github.com/reduxframework/redux-framework/

# list if additional links on the footer
footerLinks:
  - title: GitHub
    url: https://github.com/reduxframework/redux-framework/
  - title: Issues
    url: https://github.com/reduxframework/redux-framework/issues?state=open

# header
header:
  color1: "#003b51"
  color2: "#008cbf"
  trianglify: true

# google analytics
analytics:
  account:
  domain:

# github buttons
githubButton:
  user: reduxframework
  repo: redux-framework

# twitter buttons
twitter:
  enabled: true
  via: ReduxFramework
  hash: #Redux.io
  account: ReduxFramework

# facebook buttons
facebook:
  enabled: true
  profileUrl: https://www.facebook.com/ReduxFramework/


exclude: ['README.md', 'LICENSE', 'bower.json', 'Gemfile.lock', 'Gemfile']

gems:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap

# Build settings
markdown: kramdown